# docker-compose.yml

version: "3.9"

services:
  api:
    build: ./telemetry-lab
    container_name: connected-ops-api
    ports:
      - "8000:8000"

  dashboard:
    build: ./predictive-maint-dash
    container_name: connected-ops-dashboard
    ports:
      - "8501:8501"
    environment:
      # This is what app.py in the dashboard will read
      API_URL: http://api:8000/telemetry
    depends_on:
      - api
